### ISSUE TITLE
Cleanup is failing with latest IBM Cloud Collection 1.28.0

### ISSUE THREAD

**Issue by jainnikhil30** [jainnikhil30/ibm_cloud_tower_deploy#1]
Delete of VSI is failing with following error:

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "", "rc": 1, "resource": {}, "stderr": "\nError: Missing required argument\n\n  on ibm_is_instance_ansible_ansibletowertest2vsi.tf line 1, in resource \"ibm_is_instance\" \"ansible_ansibletowertest2vsi\":\n   1: resource ibm_is_instance \"ansible_ansibletowertest2vsi\" {\n\n\"image\": one of `boot_volume.0.snapshot,image,instance_template` must be\nspecified\n\n\`

Looks like there is a change in module and extra params are needed to delete a VSI.

**Comment by jainnikhil30** [comment]
fixed with #2

**Comment by jhutar** [comment]
Great you have caught it!
